import os
from datetime import date
from typing import List
from jinja2 import Template

from src.storage.models import Listing
from src.utils.logger import get_logger

log = get_logger(__name__)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Heavy Equipment Lead Report – {{ report_date }}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
  h1 { color: #1a1a2e; border-bottom: 3px solid #e94560; padding-bottom: 8px; }
  h2 { color: #16213e; margin-top: 30px; }
  .summary-grid { display: flex; gap: 16px; flex-wrap: wrap; margin: 20px 0; }
  .stat-card { background: white; padding: 16px 24px; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,.1); min-width: 140px; text-align: center; }
  .stat-number { font-size: 2em; font-weight: bold; }
  .high { color: #27ae60; } .medium { color: #f39c12; } .low { color: #95a5a6; } .rejected { color: #e74c3c; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 6px rgba(0,0,0,.1); }
  th { background: #1a1a2e; color: white; padding: 10px 12px; text-align: left; font-size: 0.85em; }
  td { padding: 9px 12px; border-bottom: 1px solid #eee; font-size: 0.85em; vertical-align: top; }
  tr.high { background: #eafaf1; } tr.medium { background: #fef9e7; } tr.low { background: #f8f9fa; }
  .badge { padding: 2px 8px; border-radius: 12px; font-size: 0.75em; font-weight: bold; text-transform: uppercase; }
  .badge-high { background: #27ae60; color: white; }
  .badge-medium { background: #f39c12; color: white; }
  .badge-low { background: #95a5a6; color: white; }
  .by-type-list { background: white; padding: 16px; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,.1); }
  .by-type-list li { padding: 4px 0; border-bottom: 1px solid #eee; }
  a { color: #2980b9; }
  .footer { margin-top: 40px; color: #888; font-size: 0.8em; }
</style>
</head>
<body>

<h1>Heavy Equipment Daily Lead Report &mdash; {{ report_date }}</h1>

<h2>Summary</h2>
<div class="summary-grid">
  <div class="stat-card"><div class="stat-number">{{ stats.total }}</div>Total Leads</div>
  <div class="stat-card"><div class="stat-number high">{{ stats.high_priority }}</div>High Priority</div>
  <div class="stat-card"><div class="stat-number medium">{{ stats.medium_priority }}</div>Medium Priority</div>
  <div class="stat-card"><div class="stat-number low">{{ stats.low_priority }}</div>Low Priority</div>
  <div class="stat-card"><div class="stat-number rejected">{{ stats.rejected }}</div>Rejected</div>
</div>

<h2>Search Areas Covered</h2>
<p>{{ cities_covered | join(', ') }}</p>

<h2>New Listings by Equipment Type</h2>
<div class="by-type-list"><ul>
{% for eq_type, count in stats.by_type.items() %}
  <li><strong>{{ eq_type | title }}</strong>: {{ count }}</li>
{% endfor %}
</ul></div>

<h2>Best Leads (High Priority)</h2>
<table>
  <thead>
    <tr>
      <th>#</th><th>Title</th><th>Brand</th><th>Price</th>
      <th>Location</th><th>Seller</th><th>Phone</th><th>Priority</th><th>Score</th><th>Link</th>
    </tr>
  </thead>
  <tbody>
  {% for l in best_leads %}
  <tr class="{{ l.lead_priority }}">
    <td>{{ loop.index }}</td>
    <td>{{ l.listing_title }}</td>
    <td>{{ l.brand or '—' }}</td>
    <td><strong>{{ l.price_raw or ('$' + (l.price | int | string)) if l.price else '—' }}</strong></td>
    <td>{{ l.location_full or '—' }}</td>
    <td>{{ l.seller_name or '—' }}</td>
    <td>{{ l.seller_phone or '—' }}</td>
    <td><span class="badge badge-{{ l.lead_priority }}">{{ l.lead_priority }}</span></td>
    <td>{{ l.lead_score }}</td>
    <td>{% if l.listing_url %}<a href="{{ l.listing_url }}" target="_blank">View</a>{% else %}—{% endif %}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>

<h2>All Leads</h2>
<table>
  <thead>
    <tr>
      <th>Title</th><th>Type</th><th>Year</th><th>Price</th>
      <th>City</th><th>Seller Type</th><th>Photos</th><th>Priority</th><th>Source</th>
    </tr>
  </thead>
  <tbody>
  {% for l in all_leads %}
  <tr class="{{ l.lead_priority }}">
    <td>{{ l.listing_title }}</td>
    <td>{{ l.equipment_type or '—' }}</td>
    <td>{{ l.year or '—' }}</td>
    <td>{{ l.price_raw or ('$' + (l.price | int | string)) if l.price else '—' }}</td>
    <td>{{ l.location_city or '—' }}</td>
    <td>{{ l.seller_type or '—' }}</td>
    <td>{{ l.photos_count }}</td>
    <td><span class="badge badge-{{ l.lead_priority }}">{{ l.lead_priority }}</span></td>
    <td>{{ l.source }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>

<div class="footer">
  Generated by Heavy Equipment Lead Agent &bull; {{ report_date }} &bull;
  Total processed: {{ stats.total }} | Rejected/excluded: {{ stats.rejected }}
</div>
</body>
</html>
"""


class ReportGenerator:
    def __init__(self, output_dir: str = "data/reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self.template = Template(HTML_TEMPLATE)

    def generate(self, listings: List[Listing], stats: dict, run_date: date = None) -> str:
        run_date = run_date or date.today()

        non_rejected = [l for l in listings if l.lead_priority != "rejected"]
        best_leads = sorted(
            [l for l in listings if l.lead_priority == "high"],
            key=lambda x: x.lead_score or 0,
            reverse=True,
        )[:10]

        cities_covered = sorted(set(l.search_city for l in listings if l.search_city))

        html = self.template.render(
            report_date=str(run_date),
            stats=stats,
            best_leads=best_leads,
            all_leads=non_rejected,
            cities_covered=cities_covered,
        )

        path = os.path.join(self.output_dir, f"report_{run_date}.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)

        log.info(f"Report generated: {path}")
        return path
